name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install package
      run: |
        pip install .[tests]

    - name: Run tests
      run: |
        pytest tests/

    - name: Build configuration file user interface
      working-directory: ./documentation
      run: |
        npm ci
        npm run create-json-schema
        npm run docs:build

    - name: 📚 Update GitHub pages
      # Update on merge to main
      if: github.ref_name == 'main'
      run: |
        # Move the built documentation out of working directory, in order to delete everything else afterwards
        cp -R ./documentation/docs/.vitepress/dist ../dist

        git config --local user.email "fmu-sim2seis-github-action"
        git config --local user.name "fmu-sim2seis-github-action"
        git fetch origin gh-pages
        git checkout -f --track origin/gh-pages
        git clean -f -f -d -x
        git rm -r *

        cp -R ../dist/* .

        git add .

        if git diff-index --quiet HEAD; then
          echo "No changes in documentation. Skip documentation deploy."
        else
          git commit -m "Update Github Pages"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
        fi
